
package com.learning.ws.jaxws.wsdl2java;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Sun Dec 25 07:32:04 MST 2011
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "EmployeeFault", targetNamespace = "http://jaxws.ws.learning.com/")
public class EmployeeFault_Exception extends Exception {
    public static final long serialVersionUID = 20111225073204L;
    
    private com.learning.ws.jaxws.wsdl2java.EmployeeFault employeeFault;

    public EmployeeFault_Exception() {
        super();
    }
    
    public EmployeeFault_Exception(String message) {
        super(message);
    }
    
    public EmployeeFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EmployeeFault_Exception(String message, com.learning.ws.jaxws.wsdl2java.EmployeeFault employeeFault) {
        super(message);
        this.employeeFault = employeeFault;
    }

    public EmployeeFault_Exception(String message, com.learning.ws.jaxws.wsdl2java.EmployeeFault employeeFault, Throwable cause) {
        super(message, cause);
        this.employeeFault = employeeFault;
    }

    public com.learning.ws.jaxws.wsdl2java.EmployeeFault getFaultInfo() {
        return this.employeeFault;
    }
}
