package com.learning.ws.jaxws.wsdl2java;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Sun Dec 25 07:32:04 MST 2011
 * Generated source version: 2.2.5
 * 
 */
 
@WebService(targetNamespace = "http://jaxws.ws.learning.com/", name = "EmployeeService")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployeeResponse")
    @WebMethod
    public com.learning.ws.jaxws.wsdl2java.Employee getEmployee(
        @WebParam(name = "employeeId", targetNamespace = "")
        java.lang.String employeeId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeAddress", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployeeAddress")
    @ResponseWrapper(localName = "getEmployeeAddressResponse", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployeeAddressResponse")
    @WebMethod
    public java.lang.String getEmployeeAddress(
        @WebParam(name = "empId", targetNamespace = "")
        java.lang.String empId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getEmployerInformation", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployerInformation")
    @ResponseWrapper(localName = "getEmployerInformationResponse", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.GetEmployerInformationResponse")
    @WebMethod
    public java.lang.String getEmployerInformation(
        @WebParam(name = "empId", targetNamespace = "")
        java.lang.String empId,
        @WebParam(name = "state", targetNamespace = "")
        java.lang.String state
    );

    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://jaxws.ws.learning.com/", className = "com.learning.ws.jaxws.wsdl2java.DeleteEmployeeResponse")
    @WebMethod
    public void deleteEmployee(
        @WebParam(name = "employeeId", targetNamespace = "")
        java.lang.String employeeId
    ) throws EmployeeFault_Exception;
}
